# -*- coding: utf-8 -*-
"""CSE485_Deep_Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VorrufQB7QwUXk9ahI8xb0lSzfk__ypN

## Load Dataset
 Tennis Object Detection
"""

!nvidia-smi -L

pip install ultralytics

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="fGeoXTubEzS2WNRvgc9n")
project = rf.workspace("private-q8lhd").project("my-first-project-f7ynl-replh")
version = project.version(1)
dataset = version.download("yolov8")

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="VtXlKnYsGazGRj8K8Nkq")
project = rf.workspace("research-project-oe9mb").project("tennis-object-detection-with-yolo")
version = project.version(1)
dataset = version.download("yolov8")

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="VtXlKnYsGazGRj8K8Nkq")
project = rf.workspace("viren-dhanwani").project("tennis-ball-detection")
version = project.version(1)
dataset = version.download("yolov8")

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="VtXlKnYsGazGRj8K8Nkq")
project = rf.workspace("yolov8main1").project("racket-bsmjm")
version = project.version(1)
dataset = version.download("yolov8")

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="VtXlKnYsGazGRj8K8Nkq")
project = rf.workspace("hoo-gnun0").project("tennis_racket-zwby0")
version = project.version(2)
dataset = version.download("yolov8")

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="VtXlKnYsGazGRj8K8Nkq")
project = rf.workspace("hyundong-song").project("tennis-racket-4ahvr")
version = project.version(2)
dataset = version.download("yolov8")

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="VtXlKnYsGazGRj8K8Nkq")
project = rf.workspace("vision-artificial-xegbx").project("tennis-ball-mpqre")
version = project.version(1)
dataset = version.download("yolov8")

import os
import shutil
import random
import yaml
from pathlib import Path

import os, shutil, random, yaml
from pathlib import Path

# ─── CONFIG ───
DATASET_DIRS = [
    "/content/Tennis-Object-Detection-with-YOLO-1",
    "/content/tennis-ball-detection-1",
    "/content/My-First-Project-1",
    "/content/racket-1",
    "/content/tennis-racket-2",
    "/content/Tennis-Ball-1",

]
OUTPUT_DIR = "/content/merged_tennis"
MASTER_CLASSES = ["tennis_ball", "tennis_racket", "tennis_player"]
CLASS_ALIASES = {
    "tennis ball":  "tennis_ball",
    "Ball":         "tennis_ball",
    "tennis ball":"tennis_ball",
    "0":"tennis_ball",
    "tennis racket":"tennis_racket",
    "Racquet":      "tennis_racket",
    "racket":       "tennis_racket",
    "tennis player":"tennis_player",
    "Player":       "tennis_player",
    "player":       "tennis_player",
    "object": None,
    "overlap": None,
}
RANDOM_SEED = 42

# ─── HELPERS ───
def load_yaml_classes(dataset_dir):
    yaml_path = Path(dataset_dir) / "data.yaml"
    with open(yaml_path) as f:
        data = yaml.safe_load(f)
    names = data.get("names", [])
    if isinstance(names, dict):
        names = [names[i] for i in sorted(names.keys())]
    return names

def build_index_remap(source_classes):
    remap = {}
    print("\n  Source class → Master class mapping:")
    for i, name in enumerate(source_classes):
        master_name = CLASS_ALIASES.get(name)
        if master_name and master_name in MASTER_CLASSES:
            master_idx = MASTER_CLASSES.index(master_name)
            print(f"    [{i}] '{name}' → [{master_idx}] '{master_name}'")
        else:
            master_idx = None
            print(f"    [{i}] '{name}' → DROPPED")
        remap[i] = master_idx
    return remap

def remap_label_file(src_path, dst_path, remap):
    kept, dropped = 0, 0
    out_lines = []
    with open(src_path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split()
            master_idx = remap.get(int(parts[0]))
            if master_idx is None:
                dropped += 1
                continue
            parts[0] = str(master_idx)
            out_lines.append(" ".join(parts))
            kept += 1
    if out_lines:
        os.makedirs(dst_path.parent, exist_ok=True)
        with open(dst_path, "w") as f:
            f.write("\n".join(out_lines) + "\n")
    return kept, dropped

def collect_pairs(dataset_dir, split):
    base = Path(dataset_dir)
    img_dir = base / "images" / split
    lbl_dir = base / "labels" / split
    if not img_dir.exists():
        img_dir = base / split / "images"
        lbl_dir = base / split / "labels"
    if not img_dir.exists():
        return []
    pairs = []
    for img_path in img_dir.iterdir():
        if img_path.suffix.lower() not in {".jpg", ".jpeg", ".png", ".bmp"}:
            continue
        lbl_path = lbl_dir / (img_path.stem + ".txt")
        if lbl_path.exists():
            pairs.append((img_path, lbl_path))
    return pairs

# ─── STEP 1: MERGE ───
random.seed(RANDOM_SEED)
out = Path(OUTPUT_DIR)

for split in ["train", "val", "test"]:
    (out / "images" / split).mkdir(parents=True, exist_ok=True)
    (out / "labels" / split).mkdir(parents=True, exist_ok=True)

total_kept = total_dropped = total_images = 0
seen_names = {"train": set(), "val": set(), "test": set()}

for ds_idx, ds_dir in enumerate(DATASET_DIRS):
    print(f"\n{'='*50}")
    print(f"Processing dataset {ds_idx+1}: {ds_dir}")
    print(f"{'='*50}")
    source_classes = load_yaml_classes(ds_dir)
    print(f"  Classes found: {source_classes}")
    remap = build_index_remap(source_classes)

    for split in ["train", "val", "test"]:
        pairs = collect_pairs(ds_dir, split)
        if not pairs:
            print(f"  [{split}] No data found, skipping.")
            continue
        print(f"  [{split}] {len(pairs)} image-label pairs")
        for img_path, lbl_path in pairs:
            stem = f"ds{ds_idx}_{img_path.stem}"
            unique_stem = stem
            counter = 1
            while unique_stem in seen_names[split]:
                unique_stem = f"{stem}_{counter}"
                counter += 1
            seen_names[split].add(unique_stem)
            dst_img = out / "images" / split / (unique_stem + img_path.suffix)
            dst_lbl = out / "labels" / split / (unique_stem + ".txt")
            shutil.copy2(img_path, dst_img)
            k, d = remap_label_file(lbl_path, dst_lbl, remap)
            total_kept += k
            total_dropped += d
            total_images += 1

print(f"\nMerge done: {total_images} images, {total_kept} annotations kept, {total_dropped} dropped")

# ─── STEP 2: 80/10/10 RESPLIT ───
print("\nResplitting 80/10/10...")

# Collect all merged image-label pairs (full paths as they exist after merge)
merged_pairs_for_resplit = []
for split in ["train", "val", "test"]:
    img_dir = out / "images" / split
    lbl_dir = out / "labels" / split
    if img_dir.exists():
        for img_file in img_dir.iterdir():
            if img_file.is_file():
                lbl_file = lbl_dir / (img_file.stem + ".txt")
                if lbl_file.exists(): # Only include pairs that have both image and label
                    merged_pairs_for_resplit.append((img_file, lbl_file))

random.shuffle(merged_pairs_for_resplit)
n = len(merged_pairs_for_resplit)
n_train = int(n * 0.80)
n_val   = int(n * 0.10)

new_splits_data = {
    "train": merged_pairs_for_resplit[:n_train],
    "val":   merged_pairs_for_resplit[n_train:n_train + n_val],
    "test":  merged_pairs_for_resplit[n_train + n_val:],
}

# Wipe and recreate ALL split directories under images/ and labels/ for the new splits
# This block was moved to AFTER the files are moved, or removed entirely if not needed.
# Since shutil.move will relocate the files, the original directories will become empty.
# The new destination directories are ensured by `mkdir(parents=True, exist_ok=True)` in the loop below.
# The initial setup also creates these directories, so re-creating them before moving is redundant
# and wiping them before moving is harmful.

# Now copy (or move) files to their new locations based on the resplit
for split, pair_list in new_splits_data.items():
    for folder in ["images", "labels"]:
        (out / folder / split).mkdir(parents=True, exist_ok=True) # Ensure destination directories exist

    for img_src_path, lbl_src_path in pair_list:
        dst_img_path = out / "images" / split / img_src_path.name
        dst_lbl_path = out / "labels" / split / lbl_src_path.name

        # Use shutil.move for efficiency, as files are already within OUTPUT_DIR
        # The `shutil.rmtree` block before this loop was removed, as it deleted the source files.
        shutil.move(img_src_path, dst_img_path)
        shutil.move(lbl_src_path, dst_lbl_path)

# Optional: Clean up any now-empty old split directories if desired, after all moves are complete.
# for split_old in ["train", "val", "test"]:
#     for folder in ["images", "labels"]:
#         if (out / folder / split_old).exists() and not any((out / folder / split_old).iterdir()):
#             shutil.rmtree(out / folder / split_old)

# ─── STEP 3: WRITE data.yaml ───
final_yaml = {
    "path":  str(out.resolve()),
    "train": "images/train",
    "val":   "images/val",
    "test":  "images/test",
    "nc":    len(MASTER_CLASSES),
    "names": MASTER_CLASSES,
}
with open(out / "data.yaml", "w") as f:
    yaml.dump(final_yaml, f, default_flow_style=False, sort_keys=False)

print("\nFinal split counts:")
for split in ["train", "val", "test"]:
    n = len(list((out / "images" / split).iterdir()))
    print(f"  {split}: {n} images")
print(f"\ndata.yaml written to {out / 'data.yaml'}")

!pip install ultralytics -q

from ultralytics import YOLO

model = YOLO("yolov8s.pt")

model.train(
    data="/content/merged_tennis/data.yaml",
    epochs=100,
    imgsz=640,
    batch=8,
    name="tennis_detector_v2",
    project="/content/runs",
    pretrained=True,
    optimizer="AdamW",
    lr0=0.0005,
    cos_lr=True,
    patience=30,
    label_smoothing=0.1,
    augment=True,
    degrees=10.0,
    fliplr=0.5,
    mosaic=1.0,
    mixup=0.1,
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4,
    scale=0.5,
    translate=0.1,
    save=True,
    plots=True,
    val=True,
    device=0,
)

model.val(
    data="/content/merged_tennis/data.yaml",
    split="test",
    plots=True,
)

!pip install yt-dlp -q
!yt-dlp -o "/content/tennis_2min.mp4" -f "mp4" "https://youtu.be/rLDm254jtZA?si=XioqP75KB4n4LNEF" --max-filesize 50m

from ultralytics import YOLO
model = YOLO("/content/runs/tennis_detector_v2-2/weights/best.pt")
model.predict(
    source="/content/tennis_2min.mp4",
    save=True,
    conf=0.3,
    iou=0.5,
    project="/content/runs",
    name="tennis_demo_1",
)